### ISSUE TITLE
Certain artist names not accepted by BeatOn/MM

### ISSUE THREAD

**Issue by kizza42** [joshwcomeau/beatmapper#28] opened 2019-10-01 09:28 UTC
Wifey and I put together a song for our Quest but we cannot get BeatOn or Mediocre Mapper to parse files that Beatmapper outputs. The file passes JSON validation but yeah can't load it anywhere 😥
Here is an example:
https://drive.google.com/file/d/1TYr1VeG-dn34UCflV8SwATOP5YRFpj0J/view?usp=sharing

**Comment by joshwcomeau** [comment] 2019-10-02 00:19
hey @kizza42, sorry to hear that!

One thought: I wonder if it's the `(short)` in the song title? No clue if there's any character restrictions but I looked at the info.dat and that's the only thing that struck me as off.

I'm away from my Quest right now but tomorrow I'll try and transfer it to BeatOn and see if I get the same error. For mediocremapper, are you exporting "legacy" files? There's a second button on the download page if you'd like to load it in MM.

Will follow up when I have more info, but let me know if either of those suggestions help!

**Comment by kizza42** [comment] 2019-10-02 08:58
We thought about that and tried stripping all the special chars out but it still fails to load. Mediocre Mapper can't load the legacy export either. If I compare the map file from your demo file on the site with our export, they differ in style, is something amiss in the exporter?

Next I tried making a new file from scratch with only 2 elements in it and have the same issue.

![beatmapper](https://user-images.githubusercontent.com/12605257/66031285-71217400-e546-11e9-9a37-0bd50ab6b012.png)

**Comment by joshwcomeau** [comment] 2019-10-02 13:14
So this is _super_ strange - it looks like the problem is this line:

```json
  "_songAuthorName": "Elle King",
```

If I change that field to any other value, everything works.

As for why the demo song and your song are in a different format, the only thing different is that the whitespace is removed in your export (to make the filesize smaller). Not entirely sure why it isn't doing the same thing for the demo song, but yeah, JSON (the file format used) isn't whitespace-sensitive so it doesn't make a difference.

My hunch is that there's something about the string "Elle King" that causes the BeatOn/MM parsers to crash. It's super weird, but yeah. I checked and Beat Saver has no songs by Elle King, so I suspect this is somehow a wide-ranging issue. As a fix, you could change the artist name to "King, Elle". Or "by Elle King". Both worked for me.

I'll leave the issue open until you can let me know if the same fix works for you, but I'm gonna rename it since it appears to be an issue with BeatOn / other tools, and not with Beatmapper itself.

**Comment by joshwcomeau** [comment] 2019-10-05 15:25
Gonna close this since I'm pretty sure I got the issue, but @kizza42 let me know if it doesn't work for you!

**Closed by joshwcomeau** 2019-10-05 15:25 UTC

**Comment by kizza42** [comment] 2019-10-05 22:41
Sorry, I was away for a few days! Yes this resolved the issue, sooo strange! Thankyou for your assistance
